### ISSUE TITLE
Load requirement.txt in setup.py

### ISSUE THREAD

**Issue by parisni** [CodeMouse92/Timecard#24]
Hi. Juste see jour fossdem presentation. What about loading the dependencies from requirement.txt within thé setup file. Having to manage duplicates can be  source of trouble ? Thanks

**Comment by CodeMouse92** [comment]
Hi @parisni, great question. In fact, the convention is to _not_ load requirements.txt in your setup.py, and quite deliberately. One major reason is that requirements.txt is not just the dependencies for the project, but *every single thing you could possibly need for a development-and-test build*. On the other hand, setup.py only lists the *requirements*, with certain optional dependencies besides.

The reason for this split is a difference in audience. `setup.py` is for the end-user, who just wants the code working with the optional features they select. They don't care about testing, generally. Meanwhile, `requirements.txt` is for the developer. When someone pulls down the source code for development, building, or testing, they want to be able to run `pip install -r requirements.txt`, and have no other installation needs before they start development or testing.

I hope that makes sense for a Sunday-afternoon-and-Jason-needs-more-coffee explaination. :)

**Comment by parisni** [comment]
I guess I get the idea. So what about splitting  dependencies in requirements.txt requirements.opt.txt and requirements.test.txt ? All could be sourced in the setup file. Thx again

**Comment by CodeMouse92** [comment]
You could, but that's kinda outside the normal convention. There's no clean and idiomatic way to include requirements.txt in the setup.py - they're all rather hacky and not recommended - because of that difference in audience.

You could still have something like `requirements.txt` and `requirements.dev.txt` or what have you, but those files should always be aimed at developers, not end-users.
